project_name: psx-memcard

builds:
  - id: default
    main: ./main.go
    binary: psx-memcard
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

archives:
  - id: default
    format: tar.gz
    files:
      - bin/*

changelog:
  use: git
